apiVersion: v1
entries:
  vaultwarden:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-05-10T03:02:21.320086+03:00"
    description: A Helm chart for Kubernetes
    digest: bf3dc2f6ff6b98efed75981a77fb76bebae6812ac9d4649e43fec049545013db
    name: vaultwarden
    type: application
    urls:
    - vaultwarden-0.1.0.tgz
    version: 0.1.0
generated: "2025-05-10T03:02:21.319367+03:00"
