apiVersion: kinda.rocks/v1beta1
kind: Database
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
	secretName: {{ .Values.db.secretName}}
	instance: postgres
	deletionProtected: true
	backup:
  	enable: false
  	cron: 0 0 * * *
	credentials:
  	templates:
    	- name: DATABASE_URL
      	template: "{{ `{{ .Protocol }}://{{ .Username }}:{{ .Password }}@{{ .Hostname }}:{{ .Port }}/{{ .Database }}` }}"
      	secret: true

### TODO
### to values 9 10